Feat/import json
NicoEvZ/Cube pull request #9
Opened 2023-12-11 09:37 UTC by NicoEvZ

Please have a look at the link and see how we can set this up.

https://github.com/DaveGamble/cJSON

2023-12-11 09:38 UTC, NicoEvZ commented
This branch will have to be rebased once PR#8 has been reviewed and merged.

2023-12-12 06:11 UTC, NicoEvZ commented
> [ ](/NicoEvZ)

Done

2023-12-22 06:35 UTC, OkeWoke requested changes
just a few nitpicks, impressive additions

2023-12-22 06:35 UTC, OkeWoke commented on lib/draw.c
> +#define CHAR_CONST 2.3
char const sounds like a C thing, maybe rename to something more descriptive

2023-12-22 06:35 UTC, OkeWoke commented on lib/draw.c
> +int importJSON(const char *file_path, data *importData_struct)
is this struct called data from cJson?
If not, maybe rename to something more descriptive

2023-12-22 06:35 UTC, OkeWoke commented on lib/draw.c
> +
don't commit commented out code.

2023-12-22 06:35 UTC, OkeWoke commented on lib/draw.c
> +void drawMeshOnScreen(mesh inputMesh, double origin[2], screenStruct screen, vector *inputVecArr)
what is inputVecArr, this is a bit of a redundant name,  maybe call it normalVectors or something?

2023-12-22 06:35 UTC, OkeWoke commented on lib/draw.c
>          return newMesh;
I would probably instead throw an error here if file not found

2023-12-22 06:35 UTC, OkeWoke commented on lib/draw.c
> +        tempVec.x = tempVec.x * CHAR_CONST;
if this char_const is purely about scaling for your ascii display, then I think this scaling logic should go in the draw function. your 2d projection shouldn't know or care about the output medium

2023-12-22 09:14 UTC, OkeWoke commented on lib/draw.c
> +int importJSON(const char *file_path, data *importData_struct)
i renamed it to renderConfig

2025-11-05 08:51 UTC, merged